[package]
name = "simp"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
scan_fmt = "0.2.6"
rand = "0.8.5"
nalgebra = "*"
num-traits = "0.2.18"
env_logger = "0.11.3"
log = "0.4.21"

[profile.release]
debug = true
